/* Copyright (c) 2015, Daniel Martí <mvdan@mvdan.cc> */
/* See LICENSE for licensing information */

package main

import (
	"log"
	"os"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/net/idna"

	"github.com/mvdan/xurls"
)

const path = "regex.go"

var regexTmpl = template.Must(template.New("regex").Parse(`// Generated by regexgen

package xurls

const (
	gtld        = ` + "`" + `{{.Gtld}}` + "`" + `
	otherScheme = ` + "`" + `{{.OtherScheme}}` + "`" + `
)
`))

// These schemes may be followed by just ":" instead of "://", so instead of
// allowing for arbitrary schemes we're limiting the regex to just a few
// well-known ones.
var schemes = []string{
	`bitcoin`,
	`magnet`,
	`mailto`,
	`sms`,
	`tel`,
	`xmpp`,
}

func writeRegex(tlds []string) error {
	allTldsSet := make(map[string]struct{})
	for _, tldlist := range [...][]string{tlds, xurls.PseudoTLDs} {
		for _, tld := range tldlist {
			allTldsSet[tld] = struct{}{}
			asciiTld, err := idna.ToASCII(tld)
			if err != nil {
				return err
			}
			allTldsSet[asciiTld] = struct{}{}
		}
	}
	var allTlds []string
	for tld := range allTldsSet {
		allTlds = append(allTlds, tld)
	}
	sort.Strings(allTlds)
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	return regexTmpl.Execute(f, struct {
		Gtld, OtherScheme string
	}{
		Gtld:        `(?i)(` + strings.Join(allTlds, `|`) + `)(?-i)`,
		OtherScheme: `(?i)(` + strings.Join(schemes, `|`) + `)(?-i):`,
	})
}

func main() {
	log.Printf("Generating %s...", path)
	if err := writeRegex(xurls.TLDs); err != nil {
		log.Fatalf("Could not write %s: %s", path, err)
	}
}
